export const PHYSICAL_KEYBOARD_CHLICK = "PHYSICAL_KEYBOARD_CHLICK";
export const VIRTUAL_KEYBOARD_CHLICK = "VIRTUAL_KEYBOARD_CHLICK";

export const ADD_PREMISE = "ADD_PREMISE";
export const REPLACE_PREMISE = "REPLACE_PREMISE";
export const DELETE_PREMISE = "DELETE_PREMISE";
export const MARKED_PREMISE = "MARKED_PREMISE";
export const SWITCH_PREMISES = "SWITCH_PREMISES";

export const ADD_CONCLUSION = "ADD_CONCLUSION";
export const REPLACE_CONCLUSION = "REPLACE_CONCLUSION";
export const DELETE_CONCLUSION = "DELETE_CONCLUSION";

export const ADD_ARGUMENT = "ADD_ARGUMENT";
export const REPLACE_ARGUMENT = "REPLACE_ARGUMENT";
export const MARKED_ARGUMENT = "MARKED_ARGUMENT";

export const GO_TO_INDEX = "GO_TO_INDEX";
